### ISSUE TITLE
Parralax scrolling jumpy on chrome

### ISSUE THREAD

**Issue by humbleRumble** [linnett/backgroundVideo#12] opened 2015-06-02 17:26 UTC
[This question was asked on stackoverflow.com](http://stackoverflow.com/q/30587428/4639281)

The issue has only been confirmed in google chrome (maybe only some versions)

> http://www.marketstreetcredit.com/test/ 

> When you scroll down the page, as soon as you pass the end of the video the header jumps up. 

![http://i.imgur.com/lNZttWh.gif](http://i.imgur.com/lNZttWh.gif)

> Notice how the header jumps up and down when you scroll past the end of the video? This doesn't happen on every browser though, so far it can only be confirmed to affect chrome.

I've noticed that this behavior is also exhibited on [this example from the readme](http://linnett.github.io/backgroundVideo/simple-example.html) (the background jumps while scrolling). So I'm inclined to believe it has to do with this script and not the users code.

**Comment by linnett** [comment] 2015-06-02 20:50
I'm just looking into this now and trying to reproduce. My examples need updating with better videos which I am going to do now.

**Comment by linnett** [comment] 2015-06-02 21:36
It seems to be working fine, see link here: http://linnett.github.io/backgroundVideo/text-overlay-example.html

It could be an issue with 3d transforms as they use the hardware. I will certainly take a look on other laptops to see if I can reproduce the error.

**Comment by humbleRumble** [comment] 2015-06-02 22:46
Awesome, thanks. Let me know what the issue was so I can post it as an answer on the question :)

**Comment by humbleRumble** [comment] 2015-06-03 00:04
Could be relevant: http://kristerkari.github.io/adventures-in-webkit-land/blog/2013/08/30/fixing-a-parallax-scrolling-website-to-run-in-60-fps/

**Comment by humbleRumble** [comment] 2015-06-03 00:23
After some research it could be related to the use of [requestAnimationFrame()](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) which can be supplemented with [this polyfill for cross-browser support](https://gist.github.com/paulirish/1579671#file-raf-js)

**Comment by linnett** [comment] 2015-06-03 10:40
This plugin does not use requestAnimationFrame(). Still taking a look

**Comment by humbleRumble** [comment] 2015-06-03 18:45
I was suggesting that it could, based on what I've read about doing operations within a scroll handler. (apparently this is not handled well on chrome)

**Comment by humbleRumble** [comment] 2015-06-05 23:06
Any updates?

**Comment by linnett** [comment] 2015-06-06 07:28
I've been in the process of moving house this week and am moving today so as you can imagine I am really busy. Trust me, it's on my radar but it will require time to go through and apply certain fixes to see which one works best. The plugin is still usable (just not perfectly smooth) so please go ahead and use it and keep an eye out in the coming days for an update

**Comment by humbleRumble** [comment] 2015-06-07 00:45
I hope the move goes well. Will be waiting for updates :)

**Comment by linnett** [comment] 2015-06-07 18:41
I've put a potential fix in using requestAnimationFrame rather than using the onScroll. The fix has been put into this branch https://github.com/linnett/backgroundVideo/tree/hotfix/12. Please let me know if this helps. I've checked and it seems absolutely fine to me. If it has improved, I will merge it back into master and close the bug

**Comment by humbleRumble** [comment] 2015-06-08 16:46
Confirmed fixed for me, I don't have access to the OP's original source code, it's down right now but using the snippet he provided and the new script, the symptom is gone.

**Closed** 2015-06-08 16:47 UTC
Labels: bug

**Comment by linnett** [comment] 2015-06-08 16:54
I've merged that back into master as you can see
